local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = "Project Find" })
vim.keymap.set('n', '<C-p>', builtin.git_files, { desc = "Telescope Git Files" })
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "Project Search" })
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>pd', builtin.diagnostics, { desc = "[Project] [D]iagnostics" })
vim.keymap.set('n', '<leader>pr', builtin.resume, { desc = "[Project] [R]esume" })
vim.keymap.set('n', '<leader>pg', builtin.live_grep, { desc = "[Project] by [G]rep" })
